### ISSUE TITLE
minimap selection shows opaque

### ISSUE THREAD

**Issue by michaeljota** [alireza-ahmadi/vscode-theme-gotham#1]
They says an image says more than 1000 words, so two images, cause it's hard to explain. 

- With the mouse pointer in the mini map, but outside the selection area
![unovering](https://user-images.githubusercontent.com/10507776/27104522-98b69578-505a-11e7-9197-8e20b58dad83.png)

- Inside the selection area
![overing](https://user-images.githubusercontent.com/10507776/27104514-93512ef4-505a-11e7-9549-8e335b5ebace.png)

I think this should be transparent, allowing to see what to select.

BTW: Awesome theme, I love it.

**Comment by alireza-ahmadi** [comment]
Nice catch, I am not a fan of minimap and it's always disabled on my editor so I missed this. I will change its behavior in the next version.

**Comment by michaeljota** [comment]
Actually, the scrollbar is also in an opaque color, hiding errors and everything behind it. Just for you to notice it.

**Comment by alireza-ahmadi** [comment]
Fixed in the latest update.

**Comment by alireza-ahmadi** [comment]
@michaeljota Overall, Thanks for your reported issues and sorry for the late action on my side.
