### ISSUE TITLE
No visual selection in menus

### ISSUE THREAD

**Issue by a118n** [alireza-ahmadi/vscode-theme-gotham#10]
![screenshot from 2018-10-24 14-16-30 - 1](https://user-images.githubusercontent.com/12648348/47426970-92ef7400-d797-11e8-83a4-2d3ca2987017.png)
![screenshot from 2018-10-24 14-16-42](https://user-images.githubusercontent.com/12648348/47426971-92ef7400-d797-11e8-81aa-a25654265e0a.png)

There's no visual selection (i.e. option under a cursor doesn't change background color) in the menus such as the ones pictured above.

**Comment by alireza-ahmadi** [comment]
🤦‍♂️ I will take a look at it.
