### ISSUE TITLE
`this` does not colorize

### ISSUE THREAD

**Issue by michaeljota** [alireza-ahmadi/vscode-theme-gotham#2]
I think this maybe a thing of taste, but I like `this` to be colorized. I like how properties are show in a bluish color, maybe `this` can be a redish color or a yellowish color, but being another color different than the one that it's being used in functions and keywords.

**Comment by alireza-ahmadi** [comment]
I will implement colorization of this if it's possible.

**Comment by alireza-ahmadi** [comment]
This issue has been fixed in the latest update.
