### ISSUE TITLE
`get` its being colorized as a keyword even when used as a function name

### ISSUE THREAD

**Issue by michaeljota** [alireza-ahmadi/vscode-theme-gotham#3]
If I have a function property called `get()` when I called it as `foo.get()` its being colorized as a keyword, in a bluedish color, but it is actually a function and should be colorized in the yellow color.

**Comment by alireza-ahmadi** [comment]
I will investigate this situation, am a little bit busy these days, but I will try to fix your reported issues and suggestions by the end of the week.

**Comment by alireza-ahmadi** [comment]
Sorry, I couldn't find any solution for this. Feel free to send a PR if you find the solution.
