### ISSUE TITLE
Shell text not legible

### ISSUE THREAD

**Issue by csMACnz** [alireza-ahmadi/vscode-theme-gotham#7]
![image](https://user-images.githubusercontent.com/1768046/27636193-349dc710-5c02-11e7-8ea2-2efb986d2265.png)

Contrast issues with one of the theme colours agains the background in the integrated console output.

Compared to `Dark (Visual Studio)` theme:

![image](https://user-images.githubusercontent.com/1768046/27636268-950e8c9c-5c02-11e7-8b44-767befa75f6c.png)

**Comment by alireza-ahmadi** [comment]
This issue has been fixed in https://github.com/alireza-ahmadi/vscode-theme-gotham/commit/e8294126f2cb54e934ce6d88f8bb1ac9e853f5ab, changes will be available in the next update.

Please let me know if the issue still exists.
